# THis information is generated by running bundle exec annotate --position before in
# Command line.

# == Schema Information
#
# Table name: users
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  # This sets it so the user can only edit their name and email.
  # Will not allow id, created_at and update_at to be modified in any way.
  attr_accessible :name, :email

end
